# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "feature/*"]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Clean Workspace
      run: rm -rf $GITHUB_WORKSPACE/*

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: List contents of the workspace
      run: ls

    # - name: Update permissions
    #   run: chmod +x $GITHUB_WORKSPACE/5-session-cleaner/6-session-cleaner

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

